# Generated by Django 5.1.5 on 2025-05-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacemedia',
            name='item',
        ),
    ]
