# Generated by Django 5.1.5 on 2025-05-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_marketplacemedia_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketplaceMedia',
        ),
    ]
