# Generated by Django 5.1.5 on 2025-05-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marketplacemedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceitem',
            name='is_swappable',
        ),
        migrations.RemoveField(
            model_name='marketplaceitem',
            name='swapp_options',
        ),
        migrations.RemoveField(
            model_name='marketplaceitem',
            name='swapp_wishlist',
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='delivery_options',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Drop-off'), ('shipping', 'Shipping'), ('meetup', 'Meet in Public')], default='pickup', max_length=50),
        ),
    ]
