# Generated by Django 5.1.5 on 2025-05-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_bio_user_profile_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_listings',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='core.marketplaceitem'),
        ),
    ]
