# Generated by Django 5.1.5 on 2025-05-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='show_countdown',
            field=models.BooleanField(default=False),
        ),
    ]
