# Generated by Django 5.1.5 on 2025-05-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_marketplaceitem_media_marketplacemedia_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacemedia',
            name='item',
        ),
    ]
