# Generated by Django 5.1.5 on 2025-05-09 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_marketplacemedia_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacemedia',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.marketplaceitem'),
            preserve_default=False,
        ),
    ]
